### ISSUE TITLE
Support stable sorting

### ISSUE THREAD

**Issue by shilangyu** [Albert221/sorted#8]
[Dart's sort method](https://api.flutter.dev/flutter/dart-core/List/sort.html) which is used by `package:sorted` is unstable.  Since this method is at the core of `package:sorted` it is not possible to use a stable sort together with `package:sorted`. I propose to add a possibility of using a stable sort.

## Proposal 1

Adding `{bool stable = false}` to `Sorted<T>.sorted` extension (with a default of `false` to not introduce any changes in behavior). Then, if stable is `true`, a stable sort would be used instead.

Standard library does not provide any stable sort algorithms. Here I see two possibilities: adding `package:collection` to dependencies which provides such algorithms but this would make `package:sorted` no longer dependency-less, or copying the implementation locally to `package:sorted` (it is not long nor complex). As for the specific implementation, we could use a merge sort which has an easy implementation but introduces $\mathcal O(n)$ space complexity (which is generally the case with stable sorts). Or if we want to get very fancy we could use some state-of-the-art stable sort implementation, like an adaptive sort ([example from rust std](https://doc.rust-lang.org/std/primitive.slice.html#impl-3)) which optimizes edge cases.

## Proposal 2

If proposal 1 is not satisfactory, instead `SortedRule` could just accept a custom sorting function, then the responsibility of space/runtime considerations and stableness/unstableness is left to the user.

Personally, I would prefer proposal 1 for its simplicity.

**Comment by Albert221** [comment]
I'm in favor of introducing the stable sort! :)

I think a blend of those two could make a pretty flexible API. `SortedRule`s only describe how to compare different elements, so we could introduce another parameter to the `sorted()` method like `sortingStrategy`.

A `SortingStrategy` would be an interface that actually sorts the list items given the sorting rules. A default could be the Dart's `List.sort`, to preserve BC, and we could also provide a merge-sort implementation.

More complex and time-performant solutions could also be implemented in the future, or by the developer by making their own sorting strategy.

As for the stable sort in our `sorted` package in general, do you think using a stable sorting algorithm as a default would be a good idea? Incrementing major version of the package is perfectly fine here.

**Comment by shilangyu** [comment]
I think sticking with Dart's default is preferred, since it's the most optimized implemention and has the most general application
